### ISSUE TITLE
On windows, 'blo in' will corrupt download of tar.gz file

### ISSUE THREAD

**Issue by rbogdanoff** [reset/berkflow#8]
If you are using Windows/MSDOS, 'blo in' command where you provide a url will corrupt the download to the tempfile.  The tempfile then fails to uncompress with Zlib.

This issues is in cli.rb, here is the snippet of code from cli.rb

if is_url?(url)
tempfile = Tempfile.new("berkflow")
begin
open(url) { |remote_file| tempfile.write(remote_file.read) }
rescue OpenURI::HTTPError => ex
error "Error retrieving remote package: #{ex.message}."
exit(1)
end
url = tempfile.path
end

On msdos if you do tempfile.binmode right after tempfile is opened, the tar.gz downloads without corruption and can then be uncompressed without failure by Zlib

**Comment by reset** [comment]
@rbogdanoff thanks for filing the issue! Any PRs are welcome to fix Windows bugs but Berkflow wasn't developed with Windows in mind and I don't have a Windows machine to dev/test things on.

**Comment by rbogdanoff** [comment]
Got it, thanks.  Yes, I don't use Windows myself (it sucks), but unfortunately half of the developers where I work are still on windows.  I am the Chef 'evangelist' here so I still need to deal with various windows pain points.  Will do a fix, test it on linux and windows and submit a PR soon
Thanks!!

**Comment by rbogdanoff** [comment]
Done, submitted PR - I put change on a branch 'issue-8'

**Comment by echohack** [comment]
I've done some testing with a custom build of berkflow and confirmed URLs now work on Windows.

Could we get an official release (0.6.3?) with this PR included?
